// Generated by CoffeeScript 1.3.3
(function() {

  this.tageswoche = this.tageswoche || {};

  tageswoche.scorecard = (function() {
    return {
      statistics: {},
      filter: {},
      data: {},
      init: function(player) {
        this.player = player;
        return this.loadStatistics(this.filter, $.proxy(this.redrawCard, this));
      },
      loadStatistics: function(filter, callback) {
        var filterString,
          _this = this;
        filterString = "";
        if (filter.location) {
          filterString += "location=" + filter.location + "&";
        }
        if (filter.competition) {
          filterString += "competition=" + filter.competition;
        }
        if (filterString === "") {
          filterString = "all";
        }
        if (this.statistics[filterString]) {
          callback(this.statistics[filterString]);
        } else {
          $.ajax({
            url: "http://tageswoche.herokuapp.com/fcb/statistics?" + filterString,
            dataType: "jsonp"
          }).done(function(data) {
            _this.statistics[filterString] = data;
            return callback(data);
          });
        }
      },
      redrawCard: function(data) {
        var value, _i, _len, _ref;
        _ref = data.list;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          value = _ref[_i];
          if (value.nickname === this.player) {
            $('#player-name').html(value.name);
            $('#minutes-played span').html(value.minutes);
            $('#games-played span').html(value.played);
            $('#goals span').html(value.goals);
            $('#assists span').html(value.assists);
            $('#yellow-cards span').html(value.yellowCards);
            $('#yellow-red-cards span').html(value.yellowRedCards);
            $('#red-cards span').html(value.redCards);
            tageswoche.formcurve.draw(value.grades);
            return;
          }
        }
      }
    };
  })();

}).call(this);
