// Generated by CoffeeScript 1.3.3
(function() {

  this.tageswoche = this.tageswoche || {};

  tageswoche.scorecard = (function() {
    return {
      statistics: {},
      filter: {},
      data: {},
      init: function(player) {
        var _this = this;
        this.player = player.replace("_", ". ");
        this.loadStatistics(this.filter, $.proxy(this.redrawCard, this));
        return $("#competition-filter").on("change", function(event) {
          var $this, _ref;
          $this = $(event.currentTarget);
          if ((_ref = _this.filter) == null) {
            _this.filter = {};
          }
          _this.filter.competition = $this.val();
          return _this.loadStatistics(_this.filter, $.proxy(_this.redrawCard, _this));
        });
      },
      getPlayerFromUrl: function() {
        return this.getUrlParameter("spieler");
      },
      getUrlParameter: function(name) {
        var value, _ref;
        value = (_ref = RegExp(name + '=' + '(.+?)(&|$)').exec(location.search)) != null ? _ref[1] : void 0;
        if (value) {
          return decodeURI(value);
        }
      },
      loadStatistics: function(filter, callback) {
        var filterString,
          _this = this;
        filterString = "";
        if (filter.location) {
          filterString += "location=" + filter.location + "&";
        }
        if (filter.competition) {
          filterString += "competition=" + filter.competition;
        }
        if (filterString === "") {
          filterString = "all";
        }
        if (this.statistics[filterString]) {
          callback(this.statistics[filterString]);
        } else {
          $.ajax({
            url: "http://tageswoche.herokuapp.com/fcb/statistics?" + filterString,
            dataType: "jsonp"
          }).done(function(data) {
            _this.statistics[filterString] = data;
            return callback(data);
          });
        }
      },
      redrawCard: function(data) {
        var value, _i, _len, _ref;
        _ref = data.list;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          value = _ref[_i];
          if (value.nickname === this.player) {
            $('#player-name').html(value.name);
            $('#minutes-played span').html(value.minutes);
            $('#games-played span').html(value.played);
            $('#goals span').html(value.goals);
            $('#assists span').html(value.assists);
            $('#yellow-cards span').html(value.yellowCards);
            $('#yellow-red-cards span').html(value.yellowRedCards);
            $('#red-cards span').html(value.redCards);
            $('#average-grade span').html(Math.floor(value.averageGrade * 10) / 10);
            tageswoche.formcurve.draw(value.grades);
            return;
          }
        }
      }
    };
  })();

}).call(this);
